### PR TITLE
Fix apache service name bug and dynamic farm loading

### PR DESCRIPTION
**Pull request by bdhoine**
Added dynamic farm loading for module idempotency

### CODE REVIEW

**Comment by bstopp** [comment]
I like this; i did not realize that the Apache configs would be updated each agent run.  (I assume that's what is happening). Is there any way to ensure the order of the farms when they are included? Their resolution needs to be deterministic. I don't think the previous implementation had a known order either.

Thoughts?

**Comment by bdhoine** [comment]
The config file indeed will change and schedule a refresh even to the Apache class. I will test the inclusion order but I assume it is in alphabetical order like filename ordering. We could add unix config like prefix parameter to force a deterministic inclusion. So for example we do it like apache dispatcher.<number>-<farm_name>.inc.any. I will update the PR with this feature and add some tests. 

By the way, if I try to run the acceptance tests a file in the files directory (other than the quickstart jar and the dispatcher module) is needed (ensure-enabled.sh). Where can I find this? Should I also update the tests to be run agains dispatcher 4.2 by default?

**Comment by bstopp** [comment]
I like the idea of using the load order similar to apache (e.g. 01-default, 02-, 10-, etc. It would require that the consumers stipulate this value in the name of the resource but as long as it is documented; i'm happy with that.

I managed to make the _ensure-running.sh_ vanish. (don't ask). for the dispatcher, you can just drop an empty file; it won't affect the acceptance tests. I'll see if i can get it back.

if you want to update to use the 4.2 dispatcher file in the nodeset definitions, be my guest; shouldn't cause any issues.

**Comment by bstopp** [comment]
Maybe we do something like priority setting in Apache puppet (https://github.com/puppetlabs/puppetlabs-apache#configuring-virtual-hosts). Something like that for the farm instances? lower priority is higher in resolution.

**Comment by bdhoine** [comment]
thats exactly what I was thinking ;)

**Comment by bstopp** [comment]
were you able to create/run acceptance tests on the updates.

**Comment by bdhoine** [comment]
No, I'm not able to run them because the shell script is missing. Waiting on this to complete the PR.

**Comment by bstopp** [comment]
I added a dummy file which should get you running acceptance tests. I can't run any at the moment due to Vagrant/VirtualBox(Guest) issues.

**Comment by bdhoine** [comment]
at first sight some tests need to be fixed, this is because they all assume the old file naming conventions, I will take a look at these and see which are failing due to the refactoring an which should pass

**Comment by bstopp** [comment]
I expected that. If/when i can get my VM's back i'll run through some checks if you have updated the acceptance tests.

**Comment by bdhoine** [comment]
I tried running the tests on the master branch but also there I'm having some errors, will update the PR in a later phase

**Pull request merged**
