### PR TITLE
Add SELinux support

### LINKED ISSUE #73: aem:dispatcher rhel7
As mentioned in the limitations, there are issues with the dependency between the aem:dispatcher and the puppet apache module. 

can you confirm that this would be causing the following:

Error: Systemd start for httpd failed!
journalctl log for httpd:
-- Logs begin at Thu 2016-12-08 09:15:15 AEDT, end at Thu 2016-12-08 10:41:44 AEDT. --
Dec 08 10:40:55 ip-172-31-7-203.ap-southeast-2.compute.internal systemd[1]: Stopping The Apache HTTP Server...
Dec 08 10:40:56 ip-172-31-7-203.ap-southeast-2.compute.internal systemd[1]: Stopped The Apache HTTP Server.
Dec 08 10:41:44 ip-172-31-7-203.ap-southeast-2.compute.internal systemd[1]: Starting The Apache HTTP Server...
Dec 08 10:41:44 ip-172-31-7-203.ap-southeast-2.compute.internal httpd[12057]: httpd: Syntax error on line 38 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.modules.d/dispatcher.load: Cannot load modules/mod_dispatcher.so into server: /etc/httpd/modules/mod_dispatcher.so: failed to map segment from shared object: Permission denied

Do you know of a work around? other than not using the aem:dispatcher class?

### PR DESCRIPTION
**Pull request by bdhoine**
If SELinux is enabled the httpd is told to be able to network connect and the correct attributes are set for the dispatcher module

Resolves #73

### CODE REVIEW

**Comment by bdhoine** [comment]
@bstopp can you please provide your feedback on this PR?

**Comment by royteeuwen** [comment]
+1. Any update on this @bstopp ?

**Comment by SimonDeSchutter** [comment]
+1

**Comment by johanruttens** [comment]
+1

**Pull request merged**
