### PR TITLE
Feature/enhanced regex rules

### PR DESCRIPTION
**Pull request by cwoeltge**
That's the first version of handling Dispatcher rule-sets to properly distinguish between POSIX and glob-style expressions.
The general idea is to make the use of POSIX explicit, like the use of `grep` or `grep -E` on bash. 
For all rule parameters, you can use `_e` to render this as POSIX with single quotes `'`, e.g. `path` or `path_e`.

Open: 
- better documentation
- updated test cases

Let's see how we can get this going.

This is an alternative solution approach to PR#106

### CODE REVIEW

**Comment by cwoeltge** [comment]
Just realizing this also has the changs of #112 and #117 - I could isolate this if required.

**Comment by henrykuijpers** [comment]
Any status update on this, @bstopp ? 

I have seen that there are/were quite a few PRs (including mine, back in 2018). Most were closed due to not being a good solution (or similar). This one is still open, but it is still not merged.

**Comment by bstopp** [comment]
This one didn't make 3.0 as it required a little more work than I was able to get done at the time. I'm aiming to update this soon.! I have not forgotten 😀

**Comment by henrykuijpers** [comment]
Any update on this, @bstopp ? We're currently working on a project that should go live within the next few months and we could really use this feature (so we can throw away our customizations).

**Comment by bstopp** [comment]
i'm working on a fix for this that should make the entire dispatcher management easier, and follow Puppet best practices. (Not to mention bringing it up to support the latest versions.)

**Comment by bstopp** [comment]
I am preparing to release a dedicated Dispatcher module here:

https://github.com/adobe/puppet-dispatcher

I will be deprecating support for the Dispatcher in this module and will not enhance it any further.

The Adobe Puppet Dispatcher module supports both regex and globs OOTB, in a much more efficient manner.

**Pull request closed without merging**
