### PR TITLE
Support regex in dispatcher config

### LINKED ISSUE #100: Dispatcher filters: Unable to use regular expressions in path/protocol/query/url
As defined in the documentation: https://helpx.adobe.com/experience-manager/dispatcher/using/dispatcher-configuration.html#ExamplefilterUsingRegularExpressions
Regular expressions can be used if the value is between single quotes instead of double quotes. However, in the erb-template the values are always encapsulated in double quotes.

### PR DESCRIPTION
**Pull request by bdhoine**
Now it is possible to define a POSIX regex in the filter config. See updated docs for more info.

Think for this PR it is best to bump the major version because the new approach is not backward compatible with existing configs (due to quotes in selector, suffix and extension now defaults to double quotes)

Resolves #100

### CODE REVIEW

**Comment by bdhoine** [comment]
@bstopp can you please provide some feedback on my implementation and fix codeclimate?

**Comment by royteeuwen** [comment]
+1. Any update on this @bstopp ?

**Comment by SimonDeSchutter** [comment]
+1

**Comment by johanruttens** [comment]
+1

**Comment by bstopp** [comment]
So i understand the need for this, and good catch for the fact i didn't include the regex support originally.

Is it necessary to do the output via a puppet function? Is there any way we can just get the syntax for the `farm` defines type to either:
* understand the properties directly? e.g. require the consumers to specify them with the right quotes within the definition? or
* have a property on the filter property itself, similar to rank, that knows how to output the string in the file correctly? This option may make the erb file a little ugly.

If we do need to have a puppet function, then it should be in a [puppet_x module](https://github.com/puppetlabs/puppet/blob/master/lib/puppet_x.rb)

**Comment by bdhoine** [comment]
I was thinking about this as well but I found out that the fact they are using single and double quotes in the config to determine the type did not make it easy to implement it in a nice way, lets keep this open and I will try to come up with a clever way to satisfy one of your points but I already thinked it through several times, any advice or suggestions here?

I never saw the Puppet module extension approach in any other modules, I will read the docs and come back later on this! Thanks for the input

**Comment by cwoeltge** [comment]
@bdhoine I got inspired by your approach but thought I don't like the "implicit" style of it too much. In fact, I don't like the Dispatcher.any approach of using the same parameter just with a different quote set too much first place, as it's the opposite as most other languages (where single quotes are to use it literally, double quotes to interpret) and not very easy to detect.
In addition, I found sections uncovered for enhanced ruleset by the original code in the dispatcher.any.erb, where rules only supported simple glob as we still wanted more parameters. 
Pls. have a look at #122 as an alternative approach. It needs more documentation and updated tests tho.

**Comment by bdhoine** [comment]
duplicate of #112

**Pull request closed without merging**
